### ISSUE TITLE
Option to enable favicons but disable preview windows?

### ISSUE THREAD

**Issue by MintMain21** [fastaddons/SearchResultPreviews#1]
**Is your feature request related to a problem? Please describe.**
I generally prefer Duck Duck Go as my search engine over similar private options like Ecosia. I've heard many argue Ecosia provides better search results (outside of the USA at least) but I always preferred the way Duck Duck Go looked for some reason. Only by trying your extension out did I realize part of the reason I preferred DDG over Ecosia or Startpage is as simple as the fact that DDG provides their own favicons while Ecosia and Startpage are without. The reason I noticed is that one of the features for your extension is the ability to generate favicons (with DDG as a optional source) when using Ecosia and Startpage. 

It's enough to make me wonder what it would look like if I could disable search previews entirely and just use the extension to generate favicons. There's a toggle to disable favicons while retaining search previews, so presumably a toggle for the opposite effect would be possible as well.

**Describe the solution you'd like**
A toggle to disable preview windows akin to the toggle to disable favicons, so that I can have favicons on Ecosia and Startpage even if I want Search Previews disabled. 

**Describe alternatives you've considered**
I never really used the previous Search Preview extension that this is meant to replace, so I'm unfamiliar both with it's pool of options as well as how it generates Search Preview Windows. Perhaps with better quality options to fine tune the Search Previews themselves I wouldn't mind having it permanently enabled, but just the ability to have search favicons alone is enticing to me.

**Additional context**
I realize the irony of suggesting this when the whole point of the extension is the search previews, but I think there are a lot of possibilities in the future for this extension to better fine-tune the search engine experience across multiple different providers.

**Comment by fastaddons** [comment]
Actually I planned to add this option, there just wasn't enough time since I needed to release it before the deadline and initial review time in stores can take a full week.

I'll try to add option "Don't show search previews" in the Settings in the next release.

**Comment by fastaddons** [comment]
Done, in version 1.2 there is a new Setting called "Hide search previews (favicon-only mode)".
Already available to Firefox.
Chrome version is being reviewed (which can take a few hours or days).
