### ISSUE TITLE
Google search issue image and right info column

### ISSUE THREAD

**Issue by GrosBourrin** [fastaddons/SearchResultPreviews#12]
Firefox 112 x64 - windows 10 x64

The right infobar is polluated by some imgs as on the following pic
![firefox_S3YTjbRNT5](https://user-images.githubusercontent.com/40931468/232305822-d1b21b42-15ba-4bdb-babc-b3d5496fd7d6.jpg)

**Comment by thepick** [comment]
I just logged-in to report this, too.

**Comment by Juraj-Masiar** [comment]
This should be now fixed in the new 4.3 version (available for Firefox, Chrome/Edge stores are reviewing the update).
