### ISSUE TITLE
Previews no longer work on duckduckgo 

### ISSUE THREAD

**Issue by delano8** [fastaddons/SearchResultPreviews#13]
**Describe the bug**  
Previews no longer work on duckduckgo 

**Steps To Reproduce**  
Search anything on duckduckgo and there are no previews whatsover. Google still works. Duckduckgo is enabled in settings and did work until about 1 day ago.

Favicons still work, even if I change the setting to get the favicons from duckduckgo (it was on google before)

**Expected behavior**  
Show previews on duckduckgo as well.

**Device info:**
 - operating system: windows 10 pro
 - Browser and version: firefox 113.0.1
 - "Search Result Previews" version: 3.4

**Additional info**
Thanks!

**Comment by MyUncleSam** [comment]
I can confirm that previews on duckduckgo are not working on my setup:
- Windows 11 Pro
- Brave Browser (Chrome based)

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry for the delay! Luckily someone wrote me an email because I see my notifications for this repo were off!
In any case, new version 3.5 fixes this and has now been released for Chrome / Firefox (rest will follow soon).
