### ISSUE TITLE
Startpage + Suggestion

### ISSUE THREAD

**Issue by Quostos** [fastaddons/SearchResultPreviews#16]
Problem:
Firefox browser

I tried the application, it is really good in its utility

But it is a real regret to note that even if the function to enable it with "Startpage"
appears in the options, unfortunately it doesn't work (or no longer works) and it's really a shame :(

Suggestion:
If possible it would be great if it could also be used with "Mojeek"
or with some more other various "no-tracking" search engines

Thank you for your kind attention

**Comment by Quostos** [comment]
24.11.2023
Starpage, now it's currently working :)
We hope this addon continues to gain attention and compatibility
Thank you

**Comment by Juraj-Masiar** [comment]
Hello,
Mojeek.com support will be available in the upcoming release 4.1. This release will also fix currently broken Startpage.com integration. I will try to release it today or tomorrow.
