### ISSUE TITLE
Add-On Error

### ISSUE THREAD

**Issue by Werner-St** [fastaddons/SearchResultPreviews#19]
On April 15th the Startpage.com page was changed, since then the search preview add-on no longer works on Firefox ! Please revise again.

Thanks

**Comment by Juraj-Masiar** [comment]
Thank you for the report!
I'll try to fix it later today.

**Comment by Juraj-Masiar** [comment]
Done, 4.1 has been released for Firefox now. Other browsers are reviewing so that will likely take a day or few.
Thanks again for reporting this.
