### ISSUE TITLE
google.com works google.Country doesn't work for example google.de

### ISSUE THREAD

**Issue by tyl0re** [fastaddons/SearchResultPreviews#2]
**Describe the bug**  
google.com works google.Country doesn't work for example google.de

**Comment by fastaddons** [comment]
Hello,
Some providers needs to be enabled manually - click the toolbar icon to open the popup window and you should see a button to enable it for the "google.de" host.

**Comment by tyl0re** [comment]
Thanks , i have looked in the settings in the plugin not in the settings in the menu when hitting the symbol. Thanks  Alot
