### ISSUE TITLE
No longer working on Ecosia

### ISSUE THREAD

**Issue by floviolleau** [fastaddons/SearchResultPreviews#23]
**Describe the bug**  
Previews no longer work on Ecosia.org

**Steps To Reproduce**  
Search anything on ecosia and there are no previews whatsover. Google still works. Ecosia is enabled in settings and did work some days ago.

Favicons still work.

![image](https://github.com/user-attachments/assets/cc2b1ab5-b150-4d04-b8c5-a334edf4b75d)

**Expected behavior**  
Show previews on Ecosia like before :).

**Device info:**
 - operating system: Ubuntu 24.10
 - Browser and version: Firefox 133.0 x64 deb version
 - "Search Result Previews" version: 5.0.2

Thanks!

**Comment by Juraj-Masiar** [comment]
Thanks for the report.
I'll try to fix and release it today or tomorrow.

**Comment by floviolleau** [comment]
Amazing :+1: :hugs:

**Comment by Juraj-Masiar** [comment]
Fixed in 4.5, auto-update should happen within 24h in Firefox, other stores are still reviewing it.

**Comment by floviolleau** [comment]
Thanks!

**Comment by floviolleau** [comment]
Works fine :clap:
