### ISSUE TITLE
HELP me find out how fast the images loads in "far away" places, like Asia or US

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/SearchResultPreviews#3]
My server is in Germany, so EU should have a fast image load.
But US and Asia regions may be too far for images to load fast enough, that is if they are not cached yet in the browser.

If you are outside of Europe, could you make a short video of some random search and post it here?
Thanks!

**Comment by alb-xss** [comment]
You should use a CDN like Cloudflare. It also has a free tier, with 275 datacenters all over the world it will serve the images from user nearest cached location. It will also save you a lot of bandwitdh costs.

**Comment by fastaddons** [comment]
Their website doesn't say much about the free tier, but I'll check it out!
Also I can't really tell how much traffic I'm currently using, I just know there are millions of thumbnails to be served.
Also with my current VPS I don't pay for traffic, so there is no bandwidth cost :).

I just wanted to improve the ping, but from the short experiments I've done it seems my current VSP in Germany can be accessed from around the world with up-to 200ms.
So maybe I don't need more servers at all?

**Comment by alb-xss** [comment]
I highly doubt that Asia-Pacific region is served with < 200ms latency from Germany. With the CDN you won't need more servers anyway, static content like images will be cached in the CDN datacenter near the final user, greatly improving latency.

**Comment by fastaddons** [comment]
I have one server in Singapore and I can ping it from here (Slovakia) with 160ms.
I planned to use it as cache for Asia region.
Sure the CDN can be great, but I'll need to check the pricing. My budget is crazy limited since as addon developer I make only very little money.
