### ISSUE TITLE
Please support weAutoPagerize

### ISSUE THREAD

**Issue by sleek22** [fastaddons/SearchResultPreviews#6]
**Update: Actually, this is working now. I had tested it after the update for uAutopagerize and it wasn't working, but I've updated it a few times since then and something has changed because it's now working.**

Thumbnails only appear on the first page.

https://addons.mozilla.org/en-US/firefox/addon/weautopagerize/

If it helps as regards coding, it used to work on the add-on that this add-on replaces.

**Comment by fastaddons** [comment]
Hello,
I've fixed it in 2.6 version, but so far only in Firefox and Edge. Chrome is still reviewing it (for a week now).
