### ISSUE TITLE
Alternative thumbnail storage

### ISSUE THREAD

**Issue by inlife** [fastaddons/SearchResultPreviews#7]
Hey @fastaddons 

Thank you so much for picking up the Search Preview mantle!

One question I have, how do you think: Would it be possible to add an alternative thumbnail mode that would leverage on-device capture & storage capacity? Basically, remove the need to have a single stationed server somewhere and become a fully self-served service/extension.

Cheers!
Vlad

**Comment by fastaddons** [comment]
Hello Vlad,
What's the motivation behind having a local server?
There are millions of thumbnails on the server taking hundreds of gigabytes, you want to have portion of that on your PC?
Also generating your own thumbnails is dangerous as some search results may point to infected pages, probably even 0-day vulnerabilities.

**Comment by inlife** [comment]
Got it! I underestimated space requirements :)

Thanks!
